---
title: "AS"
output: html_document
date: "2022-11-03"
---

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("FRASER")

library(FRASER)
library(ggpubr)
```


```{r}
library(RSQLite)
library(rhdf5)

filedb<-file.choose()
txdb_cnag<-loadDb(filedb)

filejunctions <- file.choose()
junctions <- readRDS(filejunctions)
fileh5junctions <- file.choose()
View(h5ls(fileh5junctions))
count_junctions<-h5read(fileh5junctions, "assay001")
dim(count_junctions)
rownames<- junctions@colData@rownames
colnames(count_junctions)<- rownames
head(count_junctions)
junctionsdata<-data.frame(junctions@rowRanges)
junctionsdata<-junctionsdata[c("seqnames","start","end","width","strand","startID","endID")]

junctionCts<-cbind(junctionsdata,count_junctions)
junctionCts<-junctionCts[,1:47]
#saveRDS(junctionCts, "junctionCts.rds")


filesplicesite <- file.choose()
splicesites <- readRDS(filesplicesite)
fileh5splicesites <- file.choose()
View(h5ls(fileh5splicesites))
count_splicesite<-h5read(fileh5splicesites, "assay001")
dim(count_splicesite)
colnames(count_splicesite)<- rownames
head(count_splicesite)
splicedata<-data.frame(splicesites@rowRanges)

spliceSitesCts<-cbind(splicedata,count_splicesite)
spliceSitesCts<-spliceSitesCts[,1:47]
#saveRDS(spliceSitesCts, "spliceSitesCts.rds")
```

```{r}
annots <- file.choose()
annots<-read.table(annots, sep = '\t', header = TRUE)
annots<- data.frame(annots)
colnames(annots)
annots<-annots[c("sampleID","DNA_ID","BATCH","Sex")]
annots<- annots[c(annots$BATCH=="Robleslui_01" | annots$BATCH=="Robleslui_02"),]
head(annots)
library(writexl)
write_xlsx(annots,"C:/Users/usuario/Desktop/FRASER FILES/ID_muestras_CNAG_H12O.xlsx")

```

```{r}
fds <- FraserDataSet(colData=annots, junctions=junctionCts, spliceSites=spliceSitesCts)
#saveRDS(fds, "fds.rds")
fds
```

```{r}
fds_PSIValues <- calculatePSIValues(fds)
#saveRDS(fds, "fds_PSIValues.rds")
```

```{r}
fds_filtered_ALL <- filterExpressionAndVariability(fds_PSIValues, minDeltaPsi=0.0, filter=FALSE)
#saveRDS(fds, "fds_filtered_ALL.rds")


options(repr.plot.width=5, repr.plot.height=4)
plotFilterExpression(fds_filtered_ALL, bins=100)
plotFilterVariability(fds_filtered_ALL, legend.position = c(0.5, 0.9))
```

```{r}
fds_filtered <- fds_filtered_ALL[mcols(fds_filtered_ALL, type="j")[,"passed"],]
fds_filtered

#Guardamos el objeto para no volver a repetir el proceso desde el principio
#saveRDS(fds_filtered, "fds_filtered.rds")
#Si el programa no responde iniciaremos desde este objeto
#filefdsfiltered <- file.choose()
#fds_filtered <- readRDS(filefdsfiltered)

```
El logit es el logaritmo de, en este caso, el valor de psi5. Aquí podemos ver si existe algún tipo de correlación dependiente de las muestras. En este caso vemos que efectivamente tenemos una correlacón ligada al BATCH. Nos sucede con los tres parámetros. 

```{r}
plotCountCorHeatmap(fds_filtered, type="psi5", logit=TRUE, normalized=FALSE, annotation_col=c("Sex", "BATCH"))
plotCountCorHeatmap(fds_filtered, type="psi3", logit=TRUE, normalized=FALSE, annotation_col=c("Sex", "BATCH"))
plotCountCorHeatmap(fds_filtered, type="theta", logit=TRUE, normalized=FALSE, annotation_col=c("Sex", "BATCH"))
```
Podemos revisar también los 100 intrones más variables por muestra.

```{r}
plotCountCorHeatmap(fds_filtered, type="psi5", logit=TRUE, normalized=FALSE,
plotType="junctionSample", topJ=100, minDeltaPsi = 0.01, annotation_col=c("Sex", "BATCH"))
plotCountCorHeatmap(fds_filtered, type="psi3", logit=TRUE, normalized=FALSE,
plotType="junctionSample", topJ=100, minDeltaPsi = 0.01)
plotCountCorHeatmap(fds_filtered, type="theta", logit=TRUE, normalized=FALSE,
plotType="junctionSample", topJ=100, minDeltaPsi = 0.01)
```

```{r}
set.seed(42)

fds_psi5 <- optimHyperParams(fds_filtered, type="psi5", plot=FALSE)
bestQ(fds_psi5, type="psi5")
plotEncDimSearch(fds_psi5, type="psi5")

fds_psi3 <- optimHyperParams(fds_filtered, type="psi3", plot=FALSE)
bestQ(fds_psi5, type="psi3")
plotEncDimSearch(fds_psi5, type="psi3")

fds_theta <- optimHyperParams(fds_filtered, type="theta", plot=FALSE)
bestQ(fds_psi5, type="theta")
plotEncDimSearch(fds_psi5, type="theta")

```

```{r}
fds_fitted_p <- FRASER(fds_filtered, q=c(psi5=2, psi3=2, theta=2))
```
```{r}
try({
  fds_fitted_p_a <- annotateRanges(fds_fitted_p, GRCh=38)
  rowRanges(fds, type="psi5")[,c("hgnc_symbol")]
})

plotAberrantPerSample(fds_fitted_p_a)
```


```{r}
res <- as.data.table(results(fds_fitted_p_a))
res
```


```{r}
resAsGR <- makeGRangesFromDataFrame(res, keep.extra.columns = TRUE)

# group results by genes/sample
results_by_genes <- as.data.table(resultsByGenes(resAsGR))
results_by_genes
```
```{r}
plotExpression(fds_fitted_p_a, type="psi5", result=res[sampleID == "AW7805_7599AG" & hgncSymbol == "MLH3"][1])
plotExpression(fds_fitted_p_a, type="psi3", result=res[sampleID == "AW7805_7599AG" & hgncSymbol == "MLH3"][2])
plotExpression(fds_fitted_p_a, type="theta", result=res[sampleID == "AW7805_7599AG" & hgncSymbol == "MLH3"][3])

```
```{r}
options(repr.plot.width=150, repr.plot.height=9)

res2plot <- res[sampleID == "AW7805_7599AG" & hgncSymbol == "MLH3"][1,]

plotVolcano(fds_fitted_p_a, type="psi5", "AW7805_7599AG")
plotVolcano(fds_fitted_p_a, type="psi3", "AW7805_7599AG")
plotVolcano(fds_fitted_p_a, type="theta", "AW7805_7599AG")
plotExpression(fds_fitted_p_a, result=res2plot)
plotQQ(fds_fitted_p_a, result=res2plot)
plotExpectedVsObservedPsi(fds_fitted_p_a, result=res2plot)
```

